### ISSUE TITLE
Фильтрация IP в рамках одного кластера

### ISSUE THREAD

**Issue by NotColdSkin** [Vladless/Solo_bot#101]
❤️

Просьба добавить функцию фильтрации IP-адресов на всех серверах с возможностью включения или отключения этой фильтрации (учитывая, что она может быть не всем необходима)

**Пример:** 
При покупке подписки пользователь получает доступ к нескольким серверам в пределах одного кластера. Сейчас возможна ситуация, когда пользователь делится своим ключом с другими:  
- Владелец ключа подключается к Германии с 3 устройств
- Второй человек использует ключ для подключения к Швеции с 2 устройств
- Третий подключается к Турции с 5 устройств

Таким образом, один ключ используется с нескольких разных IP-адресов

Ограничить использование нескольких IP при подключении к одному серверу возможно (правда, на самом сервере), поэтому прошу реализовать функцию, которая позволяет ограничить использование одного ключа одним IP одновременно на всех серверах сразу

При смене IP должно оставаться подключенным только последнее устройство, а подключения с предыдущих устройств должны блокироваться, например, на 15 минут

Если это вообще технически возможно реализовать со стороны бота 🤕

**Comment by Vladless** [comment]
Технически от бота это возможно реализовать, но это будет сложно через промежуточный пропуск трафика клиента. Основные ограничения делегированы на панель 3x-ui.
