### ISSUE TITLE
Функции

### ISSUE THREAD

**Issue by NotColdSkin** [Vladless/Solo_bot#103]
1. Просьба реализовать функцию, которая отслеживает доступность серверов и уведомляет активных пользователей, если сервер не отвечает на ping более 120 секунд
**Пример:** https://imgur.com/dBS2nIs

2. В последних обновлениях убрана возможность самостоятельно задавать имя устройству — теперь названия ключей генерируются автоматически. Однако, если пользователь с пробным периодом нажмёт «➕ Устройство» в «Личном кабинете», бот запросит название ключа, но само устройство (ключ) создано не будет. Огромная просьба починить 

UPD:

3. Просьба реализовать функцию дарения подписки 

Спасибо!! ❤️

**Comment by Vladless** [comment]
1. Мы ведем работу над добавлением функционала, связанным с серверами. Уже реализован полный менеджмент по добавлению и удалению кластеров и серверов прямо из админки, это позволяет не лезть лишний раз в файл конфигурации, при этом после добавления нового сервера бота теперь не обязательно перезагружать. Именно на базе этого будет добавлен мониторинг серверов в скором обновлении

2. Оперативно починено 4 дня назад

3. Гифты реализуем чуть позже, спасибо за понимание.

P.S. За новыми версиями советуем следить на сайте https://pocomacho.ru/solonetbot/ , на GitHub останутся только релизы.
