### ISSUE TITLE
Метод 'upsert_user' импортируется из локального файла database.py

### ISSUE THREAD

**Issue by hteppl** [Vladless/Solo_bot#106]
Метод [`upsert_user` ](https://github.com/Vladless/Solo_bot/blob/5be9632c5e81e7505908e537cbc0140be3c4dd91/middlewares/user.py#L6) сейчас импортируется из файла database.py, расположенного в локальной директории файла user.py. Однако судя по логике, он должен импортироваться из database.py, находящегося в корневой директории проекта. 

https://github.com/Vladless/Solo_bot/blob/5be9632c5e81e7505908e537cbc0140be3c4dd91/middlewares/user.py#L6

![{E2F431D6-751D-4FA7-ABDA-F61542227CF2}](https://github.com/user-attachments/assets/2ded5636-da59-41aa-b575-d8fbe347ba29)

**Comment by Vladless** [comment]
В проекте используются абсолютные пути импорта, поэтому в данном случае  upsert_user как раз таки импортируется из файла database.py из корневой директории бота:)
