### ISSUE TITLE
На счёт версии 3.2.2

### ISSUE THREAD

**Issue by KoPobkaTopta** [Vladless/Solo_bot#114]
В последней версии нету при покупке выбора сервера(Типо страны)? Вродь с какой-то версии было, куда ушло?Или я опять что-то не донастроил...

**Comment by Vladless** [comment]
Я не знаю, что вы недонастроили, ведь вы это делали без меня. 

Ответы на вопросы, подобные вашим, обычно даются после покупки. В поддержке дословно объясняется устройство бота, и его метод работы, в том числе и то, как работает выбор сервера в новых версиях и для чего нужны кластеры:)

Перейдите на сайт: 
https://pocomacho.ru/solonetbot/dashboard

или обратитесь в поддержку:
https://t.me/solonet_sup

Мы открыты к диалогу, но вы так и не обращались, губя разработку.
