### ISSUE TITLE
Выбор страны

### ISSUE THREAD

**Issue by KoPobkaTopta** [Vladless/Solo_bot#121]
Хотелось бы видеть в будущих версиях **выбор страны** **перед** **покупкой** (ну или переключатель хотя бы в конфиг-файле), так как в новых версиях используется балансир. Как-то не хочется переходить на старую версию ради выбора страны...

В таком случае сделать ссылку на подписку, взяв из базы. Когда же мы добавляем сервер, то вводим ссылку на подписку, так ведь? Вот её можем использовать, чтобы выдать клиенту корректную ссылку в зависимости, какую страну он выбрал.

**Comment by ResetVPN** [comment]
Так в новой версии ты создаешь кластер, где может быть любое количество локаций. Пользователь может переключаться с локации на локацию без ограничений в своём приложении.

**Comment by ResetVPN** [comment]
Не совсем понял тейка про "давать сразу 3 сервера". Есть клиент и один ключ, от того, сколько бы серверов в подписке не было, 1 подписка = 1 ключ = 1 пользователь = 1 подключение к серверу.

Если речь идёт о том, что в подписке пользователь можешь зашарить ссылку на ключ друзьям/знакомым/в интернете, то проблема решается через IP Limit уже на стороне вашей панели/дедика.

**Comment by KoPobkaTopta** [comment]
В последней версии клиенту даётся в 1 ссылке несколько серверов, если их добавить через админку в кластер. Добавил он, допустим, в Хадифи, и в прокси у него там и Франция, и Германия, и т. д. Вот этого и не хочу.

**Comment by Akhmad995** [comment]
Вы можете в одном кластере добавить только один сервер и все, сколько серверов столько и кластеров

**Comment by KoPobkaTopta** [comment]
> Вы можете в одном кластере добавить только один сервер и все, сколько серверов столько и кластеров

Ну тогда где выбор страны как в версии 1.4 перед покупкой? Именно этого и не хватает

**Comment by Vladless** [comment]
Будет в новой версии бота
