### ISSUE TITLE
config.py

### ISSUE THREAD

**Issue by PetinEvgen** [Vladless/Solo_bot#32]
Добрый день.
Можете подсказать, пожалуйста, как должен выглядеть этот файл.
Не совсем понял, как прописывать, так как в машине пишет ошибки, что недостаточно информации для запуска.

**Comment by Vladless** [comment]
Здравствуйте!
Бот выложен на гитхаб исключительно в ознакомительных целях и не предполагает бесплатную поддержку пользователей для реализации коммерческих проектов. 
Если вы желаете запустить бота и получить полную поддержку что и как куда писать, можете обратиться в поддержку бота, но данная услуга уже не бесплатна
