### ISSUE TITLE
Урезанная версия ?

### ISSUE THREAD

**Issue by Maandraj** [Vladless/Solo_bot#58]
Выглядит довольно классно, хотел потыкать. 
Так и не понял, данный репозиторий - это урезанная версия или нет ?

**Comment by Vladless** [comment]
Здравствуйте,
Для запуска бота недостает нескольких главных файлов:
config.py — все ваши технические данные данные по подключению к серверам (мультисерверность), учетные данные подключений.
Texts.py — файл по перенастройке всех описаний и цен в боте под Вас.
docker-compose.yml — необязательный, но если вы работаете с докером пригодится

Я постоянно улучшаю код и трачу на это много времени, также добавляю функции по запросу (недавно была реализована админ-панель). 
полный код лается только в поддержке бота, бот вы можете найти в конце описания проекта
